server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/weather_station?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
